var myfavs = [
    {
        cat: 'my favorites',
        name: 'Barbican Centre',
        address: 'EC2Y 8DS',
        city: 'london',
        lat: 51.5204543,
        lng: -0.0937136999999666,
        description: 'Great venue for music, cinema and exhibitions.',
        url: 'http://www.barbican.org.uk/',
        img: '',
        type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Google',
        address: 'SW1W 9tq',
        city: 'london',
        lat: 51.49496560000001,
        lng: -0.14667389999999614,
        description: 'The Mothership',
        url: 'https://www.google.com',
        img: '',
        type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Barbican Cinemas Cafe',
        address: 'Beech Street',
        city: 'london',
        lat: 51.5205906,
        lng: -0.09486970000000383,
        description: '<p>Besides showing movies of great quality from all over the world, this is also a friendly ' +
        'space open</p><p> to the public used by people to work, teach, learn, meet etc...</p><p>I do a lot of ' +
        'coding here...</p>',
        url: '',
        img: '',
        type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Silicon Roundabout',
        address: 'EC1Y 1BE',
        city: 'london',
        lat: 51.52567029999999,
        lng: -0.08756149999999252,
        description: 'London\'s answer to Silicon Valley. Dirty, smogged, dangerous, noisy. Ugly!',
        url: '',
        img: '',
        type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Shoreditch High Street station',
        address: 'Shoreditch High Street station',
        city: 'london',
        lat: 51.52338,
        lng: -0.07521999999994478,
        description: 'HERE BE HIPSTERS!',
        url: '',
        img: '',
        type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Apple store',
        address: 'W1B 2EL',
        city: 'london',
        lat: 51.5142651,
        lng: -0.14222989999996116,
        description: 'First store to open in Europe in 2004',
        url: 'http://tinyurl.com/kwo7qnz',
        img: '', type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Boxpark shoreditch',
        address: 'E1 6gy',
        city: 'london',
        lat: 51.52338109999999,
        lng: -0.07573070000000826,
        description: 'popup stores and interesting street foods. very HIP! do not come here unless you sport a ' +
        'modern beard',
        url: '',
        img: '',
        type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Silicon Milkroundabout',
        address: 'E1 6QL',
        city: 'london',
        lat: 51.5217064,
        lng:  -0.0722892999999658,
        description: '',
        url: '',
        img: '',
        type:'readonly',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Royal Festival Hall',
        address: 'SE1 8XX',
        city: 'london',
        lat: 51.5055375,
        lng: -0.1156066,
        description: '',
        url: '',
        img: '',
        type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'London Hackspace',
        address: 'E2 9DY',
        city: 'london',
        lat: 51.531801,
        lng: -0.060318,
        description: 'Great space for hacking and building things.',
        url: 'https://london.hackspace.org.uk/',
        img: '',
        type:'my favourites',
        visible:true
    },
    {
        cat: 'my favorites',
        name: 'Impact Hub Westminster',
        address: 'SW1Y 4TE',
        city: 'london',
        lat: 51.5078348,
        lng: -0.1316065,
        description: '',
        url: 'http://westminster.impacthub.net/',
        img: '',
        type:'my favourites',
        visible:true
    },
];
